### ISSUE TITLE
LXPanel and/or the task bar plugin grows in width above the configured size.

### ISSUE THREAD

**Issue by johnfound** [lxde/lxpanel#29] opened 2021-05-15 21:46 UTC
When opening too many programs, the width of LXPanel starts to grow above the screen size. 

The given behavior is observed on a two monitor configuration. The panel is attached only on the one of the monitors. Not sure whether this shows up on single monitor computers.

Also, it is not sure what is the immediate reason -- LXPanel expands itself in attempt to accommodate the wider task bar, or the task bar grows by itself and LXPanel width is simply the sum of the elements on it.

I am expecting, when the count of the open task grows, the task buttons to shrink in order to stay on the screen. In this relation it seems strange that there is an option "Maximum width of task button" while on my opinion, there should be an option "Minimum width of task button". Anyway, the task buttons never shrink and this IMHO is a misbehavior. 

Also, I can try to fix this problem, but will need some directions on the source. Where to look and what is the general idea/algorithms of the panel/task bar size management.

**Comment by clasatas** [comment] 2021-06-21 23:36
The same problem, starting from version 0.10.1 (at 0.10.0, everything is OK)

When adding tabs to the taskbar, it expands the screen limits and the tab width does not change (new tabs must decrease in width and taskbar must be fixed in width)

It is strange that no one has noticed it anymore, apparently the LXDE users are becoming less and less.

**Comment by clasatas** [comment] 2021-06-22 01:49
I recompiled LXPanel with GTK2, the problem was solved. So the problem is in supporting GTK3.

**Comment by clasatas** [comment] 2021-06-22 02:15
As far as I understand, it is due to this: https://sourceforge.net/p/lxde/bugs/773/  gtk3 + libwnck3

But for some reason this patch does not work.

**Comment by walshb** [comment] 2022-02-07 07:06
@clasatas bug 773 is a different problem (where the entire lxpanel is the wrong width, not just the task bar).

I believe I have fixed the bug here with https://github.com/walshb/lxpanel/tree/bw-github-bug-29

**Comment by ib** [comment] 2024-12-23 18:23
Fixed.

**Comment by ib** [comment] 2024-12-23 18:23
Fixed.

**Closed by ib** 2024-12-23 18:23 UTC
